//   any combo of altKey, ctrlKey, metaKey or shiftKey allowed acter code.
var keyboard = {
    prevent: [8,9,191],
    left10: [37,'shiftKey'],
    left: [37],
    up10: [38,'shiftKey'],
    up: [38],
    right10: [39,'shiftKey'],
    right: [39],
    down10: [40,'shiftKey'],
    down: [40],
    selectBack: [9,'shiftKey'],
    selectNext: [9],
    escape: [27],
    delete: [[8],[46]],
    redo: [90,'shiftKey','ctrlKey'],
    undo: [90,'ctrlKey'],
    rotateBack: [191,'shiftKey'],
    rotateNext: [191],
    variationBack: [190,'shiftKey'],
    variationNext: [190],
    mirror: [188],
    fillBack: [78,'shiftKey'],
    fillNext: [78],
    recenter: [36,'ctrlKey'],
}
